image: "jjanzic/docker-python3-opencv"

stages:
  - build
  - run
  - evaluate

build_project:
  stage: build
  script:
    - python -m venv venv
    - source venv/bin/activate
    - apt-get update && apt-get install libgl1 -y   # For opencv
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - echo "Installed everything!"
  artifacts:
    paths:
      - venv/

run_main:
  stage: run
  script:
    - source venv/bin/activate
    - apt-get update && apt-get install libgl1 -y
    - echo "Running main!"
    - python3 main.py --file_path ./dataset/pipeline/shorterVideo.avi --output_path ./Output.csv
  dependencies:
    - build_project
  artifacts:
    paths:
      - venv/
      - Output.csv

test_percentage:
  stage: evaluate
  script:
    - source venv/bin/activate
    - test_output=$(python3 evaluation.py --file_path ./Output.csv --ground_truth_path ./dataset/groundTruth.csv | grep -e "Score of Category I & II" | cut -c30-)
    - if [ -n "$test_output" ] && (( $(echo "$test_output" | awk '{if ($1 < 0.4) print 1; else print 0}') )); then echo "Test score is less than 0.4"; exit 1; fi
  dependencies:
    - run_main
  allow_failure: true